// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBboR2_6EmJmwWSGoCVhHTJa3GWg7ZyWqI',
    appId: '1:149324352114:web:a8c12c78d77e6ab02510eb',
    messagingSenderId: '149324352114',
    projectId: 'fir-project-bb2dc',
    authDomain: 'fir-project-bb2dc.firebaseapp.com',
    storageBucket: 'fir-project-bb2dc.appspot.com',
    measurementId: 'G-WGVFS8DX70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8-zeS9IoGfsoe3j8Fo0YuTsVaAD5UIQ',
    appId: '1:149324352114:android:f4f4f5eea5fa86e92510eb',
    messagingSenderId: '149324352114',
    projectId: 'fir-project-bb2dc',
    storageBucket: 'fir-project-bb2dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cl6BSnxR38l8y02JpBDAYtMD_Whm7OY',
    appId: '1:149324352114:ios:aec0b8f8f0a4b48f2510eb',
    messagingSenderId: '149324352114',
    projectId: 'fir-project-bb2dc',
    storageBucket: 'fir-project-bb2dc.appspot.com',
    androidClientId: '149324352114-5gvncu0usktakce9rbaga6reqlt7cktr.apps.googleusercontent.com',
    iosClientId: '149324352114-l7uk0fc89rhl1a100nn2nfnhc173699o.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3cl6BSnxR38l8y02JpBDAYtMD_Whm7OY',
    appId: '1:149324352114:ios:aec0b8f8f0a4b48f2510eb',
    messagingSenderId: '149324352114',
    projectId: 'fir-project-bb2dc',
    storageBucket: 'fir-project-bb2dc.appspot.com',
    androidClientId: '149324352114-5gvncu0usktakce9rbaga6reqlt7cktr.apps.googleusercontent.com',
    iosClientId: '149324352114-l7uk0fc89rhl1a100nn2nfnhc173699o.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBboR2_6EmJmwWSGoCVhHTJa3GWg7ZyWqI',
    appId: '1:149324352114:web:d6e3f2d0d0edd58a2510eb',
    messagingSenderId: '149324352114',
    projectId: 'fir-project-bb2dc',
    authDomain: 'fir-project-bb2dc.firebaseapp.com',
    storageBucket: 'fir-project-bb2dc.appspot.com',
    measurementId: 'G-L57ZJBPFVJ',
  );

}