import 'package:flutter/material.dart';

Color bgColor = const Color(0xff22272c);
List foundUser = [];

List packageList = [
  {
    'category' : 'All Popular',
    'name' : 'Hot Air Balloon',
    'location' : 'Himachal Pradesh',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i1.jpg',
    'time' : '2.00 PM - 5.00 PM',
    'rate' : 4.5,
    'description' : 'Himachal Pradesh is known for its picturesque landscapes, including snow-capped mountains, lush green valleys, dense forests, and clear rivers. A hot air balloon ride provides an unparalleled vantage point to take in the panoramic views of these natural wonders.',
    'price' : 6000,
  },
  {
    'category' : 'All Popular',
    'name' : 'Sinquerim Beach',
    'location' : 'Goa',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i4.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 4.5,
    'description' : 'Sinquerim Beach is known for its stunning natural beauty. The golden sandy shores stretch out invitingly, bordered by swaying palm trees and lush greenery. The beach offers a tranquil and less crowded atmosphere compared to some of the more commercialized beaches in Goa.',
    'price' : 8500,
  },
  {
    'category' : 'All Popular',
    'name' : 'Gulmarg',
    'location' : 'Kashmir',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i3.jpg',
    'time' : '2.00 PM - 5.00 PM',
    'rate' : 5.2,
    'description' : 'Gulmarg, which means "Meadow of Flowers," is true to its name. The town is surrounded by lush green meadows, colorful wildflowers, dense forests, and snow-capped mountains',
    'price' : 10000,
  },
  {
    'category' : 'All Popular',
    'name' : 'Nubra Valley',
    'location' : 'Ladakh',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i2.webp',
    'time' : '8.00 PM - 5.00 PM',
    'rate' : 4.9,
    'description' : 'Nubra Valley is often referred to as the "Valley of Flowers" and is characterized by its breathtaking landscapes. It features a unique mix of arid mountains, verdant fields, and sand dunes, creating a striking contrast.',
    'price' : 10800,
  },
  {
    'category' : 'All Popular',
    'name' : 'Eiffel Tower',
    'location' : 'Paris',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i5.webp',
    'time' : '8.00 AM - 9.00 PM',
    'rate' : 6.1,
    'description' : 'The Eiffel Tower, known as "La Tour Eiffel" in French, is a wrought-iron lattice tower situated on the Champ de Mars near the Seine River in Paris. ',
    'price' : 10200,
  },
  {
    'category' : 'All Popular',
    'name' : 'Hill Station',
    'location' : 'Manali',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i6.jpg',
    'time' : '7.00 AM - 7.00 PM',
    'rate' : 5.8,
    'description' : 'Hill stations are towns located at higher elevations, typically in mountainous regions, that offer a cool and refreshing climate, making them popular destinations for tourism and recreation.',
    'price' : 8000,
  },
  {
    'category' : 'All Popular',
    'name' : 'Gateway of India',
    'location' : 'Mumbai',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i7.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 5.4,
    'description' : "The Gateway of India is one of Mumbai's most iconic landmarks and a significant historical monument in India. Here's a detailed description of the Gateway of India:",
    'price' : 10800,
  },
  {
    'category' : 'All Popular',
    'name' : 'Jog Falls',
    'location' : 'Karnataka',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i8.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 5.7,
    'description' : 'Jog Falls is created by the Sharavati river dropping 253 m (830 ft), making it the third-highest waterfall in India after the Nohkalikai Falls with a drop of 335 m (1,099 ft) in Meghalaya[12] and the Dudhsagar Falls with a drop of 310 m (1,020 ft) in Goa.',
    'price' : 12500,
  },
  {
    'category' : 'All Popular',
    'name' : 'Statue of unity',
    'location' : 'Kevadia',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i9.webp',
    'time' : '8.00 AM - 9.00 PM',
    'rate' : 7.1,
    'description' : "The Statue of Unity is the world's tallest statue, with a height of 182 metres (597 feet),[3] located near Kevadia in the state of Gujarat, India. ",
    'price' : 10000,
  },
  {
    'category' : 'All Popular',
    'name' : "Rani's Stepwell",
    'location' : 'Patan',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i10.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 8.1,
    'description' : "Rani Ki Vav (lit. 'The Queen's Stepwell') is a stepwell situated in the town of Patan in Gujarat, India. It is located on the banks of the Saraswati River. Its construction is attributed to Udayamati, the spouse of the 11th-century Chaulukya king Bhima ",
    'price' : 8500,
  },
  {
    'category' : 'All Popular',
    'name' : "Lions Point",
    'location' : 'Lonavala',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i11.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.1,
    'description' : "Lions Point in Lonavala is a popular tourist destination known for its stunning panoramic views, especially of the Western Ghats and the surrounding valleys. Here’s a detailed description of Lions Point",
    'price' : 10000,
  },
  //todo-------------------------------> Mountain
  {
    'category' : 'Mountain',
    'name' : 'Rope way',
    'location' : 'Shimla',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m1.webp',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 7.3,
    'description' : 'The Jakhu Ropeway in Shimla is a popular tourist attraction offering a scenic journey between the Mall Road near the Church and Jakhu Temple atop Jakhu Hill. Spanning approximately 825 meters, the ride takes around 5-7 minutes each way',
    'price' : 4000,
  },
  {
    'category' : 'Mountain',
    'name' : 'Hill Station',
    'location' : 'Coorg',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m2.jpeg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.5,
    'description' : "Coorg's tranquil environment, coupled with its natural beauty and rich cultural heritage, makes it a favored destination for nature lovers, adventure seekers, and those looking to unwind amidst scenic surroundings.",
    'price' : 5000,
  },
  {
    'category' : 'Mountain',
    'name' : 'View Point',
    'location' : 'Shillong',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m4.jpeg',
    'time' : '8.00 AM - 7.00 PM',
    'rate' : 6.8,
    'description' : "The Shillong View Point at Shillong Peak is a must-visit for travelers seeking stunning views and a memorable experience of Meghalaya's natural beauty.",
    'price' : 5000,
  },
  {
    'category' : 'Mountain',
    'name' : 'Train View',
    'location' : 'Lonavala',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m5.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.6,
    'description' : "The Train View Point in Lonavala is a popular spot for train enthusiasts and nature lovers alike. Located near Lonavala railway station in Maharashtra, India, it offers stunning views of the Western Ghats and the scenic beauty of the surrounding hills and valleys.",
    'price' : 6000,
  },
  {
    'category' : 'Mountain',
    'name' : 'Hill Station',
    'location' : 'Ladakh',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m3.jpeg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 6.4,
    'description' : "Ladakh’s unique blend of natural beauty, cultural richness, and adventurous spirit makes it a sought-after destination for travelers seeking an unforgettable experience amidst the majestic Himalayas.",
    'price' : 8000,
  },
  {
    'category' : 'Mountain',
    'name' : 'Jog Falls',
    'location' : 'Karnataka',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m7.jpeg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 6.4,
    'description' : "Jog Falls is not only a scenic delight but also holds cultural significance for the local communities, making it a must-visit destination for nature enthusiasts and travelers exploring Karnataka's natural wonders.",
    'price' : 3000,
  },
  {
    'category' : 'Mountain',
    'name' : 'Mountain View',
    'location' : 'Lonavala',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m8.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.1,
    'description' : "Lonavala's mountain views and natural beauty make it a favored destination for nature lovers, adventure enthusiasts, and those seeking a peaceful retreat amidst scenic surroundings.",
    'price' : 3000,
  },
  {
    'category' : 'Mountain',
    'name' : 'Gulmarg',
    'location' : 'Kashmir',
    'img' : 'assets/images/CategoryWiseImages/MountainImages/m9.jpeg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 7.5,
    'description' : 'Gulmarg, which means "Meadow of Flowers," is true to its name. The town is surrounded by lush green meadows, colorful wildflowers, dense forests, and snow-capped mountains',
    'price' : 5000,
  },
  //todo-------------------------------> Temple
  {
    'category' : 'Temple',
    'name' : 'Kedarnath',
    'location' : 'Garhwal Himalayan',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t1.jpg',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 10.3,
    'description' : "Kedarnath holds a special place in the hearts of pilgrims and nature enthusiasts alike, offering a unique blend of spiritual serenity and natural grandeur in the lap of the majestic Himalayas.",
    'price' : 7000,
  },
  {
    'category' : 'Temple',
    'name' : 'Kashi Vishwanath',
    'location' : 'Varanasi',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t2.jpg',
    'time' : '9.00 AM - 6.00 PM',
    'rate' : 8.5,
    'description' : 'Visiting Kashi Vishwanath Temple is a profound spiritual experience for many, encapsulating the essence of devotion, history, and architectural splendor in the ancient city of Varanasi.',
    'price' : 7500,
  },
  {
    'category' : 'Temple',
    'name' : 'Tirupati Balaji Temple',
    'location' : 'Andhra Pradesh',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t3.jpg',
    'time' : '7.00 AM - 5.00 PM',
    'rate' : 5.9,
    'description' : "Tirupati Balaji Temple holds immense spiritual significance and cultural importance, serving as a beacon of faith and devotion for millions of devotees who visit to experience the divine presence of Lord Venkateswara.",
    'price' : 8000,
  },
  {
    'category' : 'Temple',
    'name' : 'Padmanabhaswamy Temple',
    'location' : 'Kerala',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t4.webp',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 4.6,
    'description' : "Padmanabhaswamy Temple stands as a symbol of Kerala's rich cultural heritage, religious fervor, and architectural grandeur, attracting devotees and visitors from around the world to experience its spiritual aura and historical treasures.",
    'price' : 5000,
  },
  {
    'category' : 'Temple',
    'name' : 'Jagannath Temple',
    'location' : 'Odisha',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t5.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 6.4,
    'description' : "Jagannath Temple in Puri is not only a place of worship but also a cultural and spiritual icon of Odisha, attracting devotees and tourists from across the globe to experience its grandeur, religious fervor, and ancient traditions.",
    'price' : 8000,
  },
  {
    'category' : 'Temple',
    'name' : 'Dwarkadhish temple',
    'location' : 'Dwarka',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t6.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 10.8,
    'description' : "Dwarkadhish Temple stands as a symbol of devotion and spirituality, attracting pilgrims and tourists alike to experience its religious ambiance, architectural grandeur, and the divine presence of Lord Krishna in the ancient city of Dwarka.",
    'price' : 9500,
  },
  {
    'category' : 'Temple',
    'name' : 'Amarnath Temple',
    'location' : 'Amarnath ',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t7.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 7.4,
    'description' : "Amarnath Temple holds deep spiritual significance for devotees of Lord Shiva, offering a unique blend of natural beauty, adventure, and religious fervor amidst the stunning landscapes of the Himalayas in Kashmir.",
    'price' : 7500,
  },
  {
    'category' : 'Temple',
    'name' : 'Kanchipuram',
    'location' : 'Tamil Nadu',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t8.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.1,
    'description' : "Kanchipuram remains a significant pilgrimage and cultural destination, offering a glimpse into South India's rich history, architecture, and religious traditions.",
    'price' : 9000,
  },
  {
    'category' : 'Temple',
    'name' : 'Swarna mandir',
    'location' : 'Amritsar',
    'img' : 'assets/images/CategoryWiseImages/TempleImages/t9.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 7.9,
    'description' : "The Golden Temple in Amritsar is not only a place of worship but also a symbol of peace, unity, and equality, making it a must-visit destination for anyone traveling to Punjab.",
    'price' : 11000,
  },
  //todo-----------------------------------------> Beach
  {
    'category' : 'Beach',
    'name' : 'Goa Beach',
    'location' : 'North Goa',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b1.jpg',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 8.3,
    'description' : "Each beach in Goa offers a unique experience, from lively parties to serene retreats, making it a favorite destination for travelers seeking sun, sand, and sea",
    'price' : 9300,
  },
  {
    'category' : 'Beach',
    'name' : 'Lily Beach',
    'location' : 'Maldives',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b3.jpg',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 8.4,
    'description' : "Lily Beach Resort offers a luxurious retreat in a stunning tropical setting, combining natural beauty with top-notch hospitality and amenities for a memorable Maldivian getaway.",
    'price' : 14500,
  },
  {
    'category' : 'Beach',
    'name' : 'Devka Beach',
    'location' : 'Diu & Daman ',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b2.jpg',
    'time' : '7.00 AM - 5.00 PM',
    'rate' : 7.6,
    'description' : "Devka Beach in Daman offers a blend of natural beauty, leisure activities, and cultural attractions, making it a popular destination for tourists seeking a coastal retreat in western India.",
    'price' : 12000,
  },
  {
    'category' : 'Beach',
    'name' : 'Wandoor Beach',
    'location' : 'Andaman Nicobar',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b4.jpg',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 5.3,
    'description' : "Wandoor Beach is a haven for nature lovers and adventure seekers, offering a blend of natural beauty, marine diversity, and recreational activities amidst the pristine surroundings of the Andaman Islands.",
    'price' : 15000,
  },
  {
    'category' : 'Beach',
    'name' : 'Marina Beach',
    'location' : 'Chennai',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b5.webp',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 7.1,
    'description' : 'Marina Beach holds a special place in the hearts of Chennai residents and is a must-visit destination for anyone exploring the cultural and natural beauty of the city.',
    'price' : 18000,
  },
  {
    'category' : 'Beach',
    'name' : 'Serenity Beach',
    'location' : 'Puducherry',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b6.jpeg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.9,
    'description' : 'Serenity Beach offers a blend of natural beauty, peaceful ambiance, and recreational opportunities, making it a favorite among travelers seeking a laid-back beach experience in South India.',
    'price' : 16500,
  },
  {
    'category' : 'Beach',
    'name' : 'Kavaratti Beach',
    'location' : 'lakshdrip ',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b7.webp',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 7.6,
    'description' : 'Serenity Beach offers a blend of natural beauty, peaceful ambiance, and recreational opportunities, making it a favorite among travelers seeking a laid-back beach experience in South India.',
    'price' : 11500,
  },
  {
    'category' : 'Beach',
    'name' : 'Anjuna Beach',
    'location' : 'North Goa',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b8.jpg',
    'time' : '9.00 AM - 5.00 PM',
    'rate' : 9.2,
    'description' : 'Anjuna Beach is not only a popular tourist destination but also a cultural hub offering a blend of natural beauty, water sports, shopping, and vibrant nightlife, making it a must-visit spot for travelers exploring North Goa.',
    'price' : 8500,
  },
  {
    'category' : 'Beach',
      'name' : 'Malvan Beach',
    'location' : 'Sindhudurg',
    'img' : 'assets/images/CategoryWiseImages/BeachImages/b9.webp',
    'time' : '8.00 AM - 7.00 PM',
    'rate' : 7.9,
    'description' : 'Malvan Beach offers a blend of natural beauty, historical charm, water sports, and culinary delights, making it a sought-after destination for travelers seeking a peaceful and culturally enriching beach experience on the Konkan coast of Maharashtra.',
    'price' : 12000,
  },
  //todo-----------------------------------------> Ancient Place
  {
    'category' : 'Ancient Place',
    'name' : 'Taj Mahal',
    'location' : 'Agra',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a1.jpeg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 5.3,
    'description' : 'Visiting the Taj Mahal is a once-in-a-lifetime experience, offering a glimpse into India’s rich cultural heritage and architectural marvels, as well as an enduring testament to love and devotion.',
    'price' : 8000,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Qutub Minar',
    'location' : 'Delhi',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a2.jpg',
    'time' : '7.00 AM - 10.00 PM',
    'rate' : 5.6,
    'description' : "Qutub Minar stands as a testament to Delhi's rich cultural and architectural heritage, reflecting the fusion of Indo-Islamic styles and the historical legacy of the Delhi Sultanate era.",
    'price' : 7000,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Jallianwala bagh',
    'location' : 'Punjab',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a4.webp',
    'time' : '8.00 AM - 6.00 PM',
    'rate' : 5.3,
    'description' : "Jallianwala Bagh remains a poignant reminder of a dark chapter in India's history and serves as a tribute to the sacrifice and resilience of those who fought for India's independence.",
    'price' : 15000,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Buland darwaza',
    'location' : 'Fatehpur sikri',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a5.webp',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 7.1,
    'description' : 'Buland Darwaza remains a significant architectural marvel and a testament to the grandeur and splendor of the Mughal era in India. ',
    'price' : 9000,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Humpi',
    'location' : 'Karnataka',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a6.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.9,
      'description' : "Hampi stands as a testament to India's rich cultural heritage and architectural marvels, attracting history buffs, archaeology enthusiasts, and travelers seeking to explore its ancient ruins and immerse themselves in its vibrant history.",
    'price' : 6500,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Sanchi',
    'location' : 'Madhya Pradesh ',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a7.webp',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 3.7,
    'description' : "Visiting Sanchi provides a profound insight into the ancient Buddhist civilization of India and its enduring cultural and architectural legacy.",
    'price' : 6000,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Mohenjo-daro',
    'location' : 'Sindh',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a8.jpg',
    'time' : '9.00 AM - 5.00 PM',
    'rate' : 11.2,
    'description' :  "Mohenjo-daro stands as a testament to the ingenuity and sophistication of one of the earliest urban civilizations in history, providing valuable insights into human civilization's development and organization during the Bronze Age",
    'price' : 10500,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Char Minar',
    'location' : 'Hyderabad',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a9.jpg',
    'time' : '8.00 AM - 7.00 PM',
    'rate' : 8.6,
    'description' : "Charminar stands as an architectural marvel and a symbol of Hyderabad’s cultural fusion of Islamic and Indian influences. It remains an enduring symbol of the city's identity and a must-visit destination for tourists exploring Hyderabad’s historical and cultural landmarks",
    'price' : 9000,
  },
  {
    'category' : 'Ancient Place',
    'name' : 'Khajuraho Temple',
    'location' : 'Madhya Pradesh',
    'img' : 'assets/images/CategoryWiseImages/AncientImages/a3.jpg',
    'time' : '7.00 AM - 5.00 PM',
    'rate' : 6.4,
    'description' : "Khajuraho Temples stand as a testament to India’s rich architectural heritage and artistic achievements, attracting tourists, historians, and art enthusiasts from around the world to",
    'price' : 7000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Athens',
    'location' : 'Greece',
    'img' : 'assets/images/culturalImages/Athens Greece/National Archaeological Museum.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 6.4,
    'description' : "Athens stands as a living testament to the enduring legacy of ancient Greece and its profound impact on Western civilization, attracting millions of visitors each year to experience its historical richness and cultural vibrancy.",
    'price' : 25000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Barcelone',
    'location' : 'Spain',
    'img' : 'assets/images/culturalImages/Barcelona Spain/Gothic Quarter.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 6.4,
    'description' : "Barcelona's dynamic blend of history, culture, art, and cuisine makes it a top destination for travelers seeking both architectural marvels and Mediterranean charm.",
    'price' : 30000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Dubai',
    'location' : 'UAE',
    'img' : 'assets/images/culturalImages/Dubail Uae/Palm Jumeirah.jpeg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 9.4,
    'description' : "Dubai’s blend of futuristic architecture, cultural richness, and luxurious experiences makes it a top destination for travelers seeking glamour, adventure, and a glimpse into the Middle East's dynamic spirit.",
    'price' : 35000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Jerusalem',
    'location' : 'Israel',
    'img' : 'assets/images/culturalImages/Jerusalem Israel/Dome of the Rock.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 4.4,
    'description' : "Jerusalem's blend of ancient history, religious significance, and cultural diversity continues to make it a compelling destination for travelers and pilgrims alike, offering a profound glimpse into the shared heritage of humanity.",
    'price' : 40000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Kyoto',
    'location' : 'Japan',
    'img' : 'assets/images/culturalImages/Kyoto, Japan/Fushimi Inari Shrine.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 5.4,
    'description' : "Kyoto's blend of ancient traditions, historical landmarks, and natural beauty continues to attract visitors from around the world, offering a glimpse into Japan's rich cultural heritage and serene landscapes.",
    'price' : 45000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Mexico City',
    'location' : 'Mexico',
    'img' : 'assets/images/culturalImages/Mexico City Mexico/Palacio de Bellas Artes.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 9.4,
    'description' : "Mexico City's blend of ancient history, colonial architecture, vibrant culture, and modern amenities makes it a captivating destination for travelers seeking a dynamic and diverse urban experience in the heart of Mexico.",
    'price' : 30000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Roman',
    'location' : 'Italy',
    'img' : 'assets/images/culturalImages/Rome Italy/Piazza Navona.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 6.4,
    'description' : "The legacy of ancient Rome continues to shape our understanding of law, governance, culture, and urban development, making it a pivotal civilization in Western history and global influence.",
    'price' : 60000,
  },
  {
    'category' : 'Cultural',
    'name' : 'Varansi',
    'location' : 'India',
    'img' : 'assets/images/culturalImages/varansi india/Assi Ghat.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 6.4,
    'description' : "Varanasi’s blend of spirituality, culture, and history makes it a captivating destination for travelers seeking a deep immersion into India’s rich cultural tapestry and religious traditions.",
    'price' : 60000,
  },
  {
    'category' : 'Family Vacation',
    'name' : 'Barrier reef',
    'location' : 'Australia',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/austellia/barrier reef.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 10,
    'description' : "The Great Barrier Reef is the world's largest coral reef system, located in the Coral Sea off the coast of Queensland, Australia. It spans over 2,300 kilometers (1,430 miles) and consists of nearly 3,000 individual reefs and 900 islands. The reef is one of the most biodiverse ecosystems on the planet, home to thousands of species of marine life, including fish, corals, mollusks, sea turtles, birds, and marine mammals.",
    'price' : 90000,
  },

  {
    'category' : 'Family Vacation',
    'name' : 'Bnaff',
    'location' : 'Canada',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/Canada/bnaff.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.4,
    'description' : "This is Canada's oldest national park, established in 1885. It covers over 6,600 square kilometers (2,564 square miles) of mountainous terrain, with glaciers, ice fields, dense coniferous forest, and alpine landscapes.",
    'price' : 94000,
  },
  {
    'category' : 'Family Vacation',
    'name' : 'Toronto',
    'location' : 'Canada',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/Canada/Toronto.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 10,
    'description' : "Toronto is the capital city of the province of Ontario and the largest city in Canada. It is known for its vibrant cultural scene, diverse population, and economic significance.",
    'price' : 10000,
  },

  {
    'category' : 'Family Vacation',
    'name' : 'Cape Town',
    'location' : 'South Africa',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/South Africa/Cape Town.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 9.4,
    'description' : "Cape Town is a vibrant city located on the southwestern coast of South Africa, often described as one of the most beautiful cities in the world.",
    'price' : 10000,
  },

  {
    'category' : 'Family Vacation',
    'name' : 'barcelona',
    'location' : 'Spain',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/spain/barcelona.jpg',
    'time' : '7.00 AM - 7.00 PM',
    'rate' : 9.8,
    'description' : "Barcelona is a vibrant and cosmopolitan city located on the northeastern coast of Spain, along the Mediterranean Sea. Known for its unique blend of modernist architecture, rich history, cultural heritage, and lively atmosphere, Barcelona offers a wide range of attractions and experiences. ",
    'price' : 94000,
  },
  {
    'category' : 'Family Vacation',
    'name' : 'Cancún',
    'location' : 'Maxico',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/Maxico/Cancún.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.4,
    'description' : "Cancún is a world-renowned tourist destination located on the northeastern coast of the Yucatán Peninsula in Mexico. Known for its beautiful white sand beaches, turquoise waters, and vibrant nightlife, Cancún attracts millions of visitors each year. ",
    'price' : 98000,
  },
  {
    'category' : 'Family Vacation',
    'name' : 'Queenstown',
    'location' : 'New Zealand',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/New zeland/Queenstown.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.4,
    'description' : "Queenstown is a resort town located on the South Island of New Zealand, nestled on the shores of Lake Wakatipu and surrounded by the dramatic Southern Alps. Known as the Adventure Capital of the World, Queenstown attracts visitors with its stunning landscapes, outdoor activities, and vibrant atmosphere.",
    'price' : 90000,
  },
  {
    'category' : 'Family Vacation',
    'name' : 'New York',
    'location' : 'USA',
    'img' : 'assets/images/CategoryWiseImages/Family Vaction Images/New york/statue of unity.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 9.4,
    'description' : "Queenstown is a resort town located on the South Island of New Zealand, nestled on the shores of Lake Wakatipu and surrounded by the dramatic Southern Alps. Known as the Adventure Capital of the World, Queenstown attracts visitors with its stunning landscapes, outdoor activities, and vibrant atmosphere.",
    'price' : 20000,
  },
  {
    'category' : 'Nature & Wildlife',
    'name' : 'Daintree Rainforest',
    'location' : 'Australia',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Australia/Daintree Rainforest.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.4,
    'description' : 'In Australia north, where emerald canopies rise,Daintree Rainforest, ancient and wise, A verdant kingdom, untouched and grand, Where life teems in every leaf and strand.',
    'price':94000,},

  {
    'category' : 'Nature & Wildlife',
    'name' : 'Chobe National Park',
    'location' : 'Botswana',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Botswana/Chobe National Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 5.4,
    'description' : "In Botswana embrace, where the rivers flow,Chobe National Park, where wild wonders grow,Savannah stretches under the African sky,Where elephants roam, majestic and high.",
    'price':80000,
  },
  {
    'category' : 'Nature & Wildlife',
    'name' : 'Algonquin Provincial Park',
    'location' : 'Canada',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Canada/Algonquin Provincial Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 6.5,
    'description' : "In Canadas heart, where wilderness reigns,Algonquin Provincial Park, nature's domains.Lakes mirror pines in their tranquil embrace,Echoes of loons across quiet space.",
    'price':75000,
  },
  {
    'category' : 'Nature & Wildlife',
    'name' : 'Lauca National Park',
    'location' : 'Chile',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Chile/Lauca National Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.5,
    'description' : "In Chile's northern expanse, where the Andes soar,Lauca National Park, wild and pure.Volcanic peaks pierce the azure sky, High-altitude lakes reflect mountains high",
    'price':80000,
  },
  {
    'category' : 'Nature & Wildlife',
    'name' : 'Podocarpus National Park',
    'location' : 'Ecuador',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Ecuador/Podocarpus National Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 7.4,
    'description' : "In Ecuador's embrace, where biodiversity thrives,Podocarpus National Park, where nature thrives.Cloud forests cloak mountains in misty veils,Podocarpus, where diversity prevails.",
    'price':10000,
  },
  {
    'category':'Nature & Wildlife',
    'name' : 'Chitwan National Park',
    'location' : 'Nepal',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Nepal/Chitwan National Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.4,
    'description' : 'In Nepal embrace, where jungles unfold,Chitwan National Park, a sanctuary bold.Rhinos roam freely in marshlands wide,Tigers prowl silently, their grace undenied.',
    'price':44000,
  },

  {
    'category' : 'Nature & Wildlife',
    'name' : 'Addo Elephant National Park',
    'location' : 'South Africa',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/South Africa/Addo Elephant National Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 5.4,
    'description' : "In South Africa's realm, where the sun's rays play,Addo Elephant National Park, where giants sway.Herds of elephants traverse the dusty plains,Their presence a testament to nature's reigns.",
    'price':56000,
  },
  {
    'category' : 'Nature & Wildlife',
    'name' : 'Lake Manyara National Park',
    'location' : 'Tanzania',
    'img' : 'assets/images/CategoryWiseImages/Nature & Wildlife/Tanzania/Lake Manyara National Park.jpg',
    'time' : '7.00 AM - 6.00 PM',
    'rate' : 8.5,
    'description' : "In Tanzania's embrace, where the Rift Valley begins,Lake Manyara National Park, where nature's beauty wins.Acacia trees stretch with elegant grace,Reflecting in the lake's tranquil embrace.",
    'price':8000,
  },
];

int selectedIndex = 0;