import 'package:flutter/material.dart';

Color bgColor = const Color(0xff22272c);

List packageList = [
  {
    'name' : 'Hot Air Balloon',
    'location' : 'Mumbai',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i1.jpg',
    'time' : '2.00 PM - 5.00 PM',
    'rate' : 4.5,
    'description' : 'hello',
    'price' : 2000,
  },
  {
    'name' : 'Gandhi Ashram',
    'location' : 'Surat',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i2.jpeg',
    'time' : '8.00 PM - 5.00 PM',
    'rate' : 4.9,
    'description' : 'hello',
    'price' : 1800,
  },
  {
    'name' : 'Sabarmati River',
    'location' : 'Ahmedabad',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i3.jpg',
    'time' : '2.00 PM - 5.00 PM',
    'rate' : 5.2,
    'description' : 'hello',
    'price' : 1000,
  },
  {
    'name' : 'Sinquerim Beach',
    'location' : 'Goa',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i4.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 4.5,
    'description' : 'hello',
    'price' : 1500,
  },
  {
    'name' : 'Iskcon Temple',
    'location' : 'Surat',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i5.jpg',
    'time' : '9.00 AM - 6.00 PM',
    'rate' : 6.1,
    'description' : 'hello',
    'price' : 1200,
  },
  {
    'name' : 'Hill Station',
    'location' : 'Manali',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i6.jpg',
    'time' : '7.00 AM - 7.00 PM',
    'rate' : 5.8,
    'description' : 'hello',
    'price' : 2000,
  },
  {
    'name' : 'Gateway of India',
    'location' : 'Mumbai',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i7.jpg',
    'time' : '7.00 AM - 8.00 PM',
    'rate' : 5.4,
    'description' : 'hello',
    'price' : 1800,
  },
  {
    'name' : 'Jog Falls',
    'location' : 'Karnataka',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i8.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 5.7,
    'description' : 'hello',
    'price' : 2500,
  },
  {
    'name' : 'Statue of unity',
    'location' : 'Kevadia',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i9.webp',
    'time' : '8.00 AM - 9.00 PM',
    'rate' : 7.1,
    'description' : 'hello',
    'price' : 3000,
  },
  {
    'name' : "Rani's Stepwell",
    'location' : 'Patan',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i10.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 8.1,
    'description' : 'hello',
    'price' : 3500,
  },
  {
    'name' : "Ram Mandir",
    'location' : 'Ayodhya',
    'img' : 'assets/images/CategoryWiseImages/AllImages/i11.jpg',
    'time' : '7.00 AM - 9.00 PM',
    'rate' : 9.1,
    'description' : 'hello',
    'price' : 3000,
  },
];